pipeline {
    agent any

    environment {
        NODEJS_VERSION = '18'
    }

    tools {
        nodejs 'node-18' // This assumes a NodeJS installation is configured in Jenkins with the name 'node-18'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('assignment-2') {
                    sh 'npm install'
                }
            }
        }

        stage('Install Playwright Browsers') {
            steps {
                dir('assignment-2') {
                    sh 'npx playwright install --with-deps'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('assignment-2') {
                    sh 'npx playwright test'
                }
            }
        }

        stage('Generate Allure Report') {
            steps {
                dir('assignment-2') {
                    sh 'npx allure generate allure-results --clean -o allure-report'
                }
            }
        }

        stage('Archive Allure Report') {
            steps {
                archiveArtifacts artifacts: 'assignment-2/allure-report/**', fingerprint: true
            }
        }
    }

    post {
        always {
            allure includeProperties: false, jdk: '', results: [[path: 'assignment-2/allure-results']]
        }
    }
}
